#lang racket

(require redex/reduction-semantics
         "../dada.rkt"
         )

; Patterns to test:
;
;                Inner             Outer              Field type Yields                              Perm when shared   Lease contents
;                --------------    -----------        ---------- ----------------------------------- ------------------ ----------------------------------------
(dada-test-share my                my                 var        (my  ()       ())                   (shared Lease-id)  (Lease-id shared ()))
(dada-test-share my                my                 shared     (our ()       ())                   our                )
(dada-test-share my                my                 atomic     (my  (atomic) ())                   (shared Lease-id)  (Lease-id shared ()))
(dada-test-share my                (lent Lease-id)    var        (my  ()       (Lease-id))           (shared Lease-id1) (Lease-id1 shared (Lease-id)))
(dada-test-share my                (lent Lease-id)    shared     (our ()       (Lease-id))           (shared Lease-id1) (Lease-id1 shared (Lease-id)))
(dada-test-share my                (lent Lease-id)    atomic     (my  (atomic) (Lease-id))           (shared Lease-id1) (Lease-id1 shared (Lease-id)))
(dada-test-share my                our                var        (our ()       ())                   our                )
(dada-test-share my                our                shared     (our ()       ())                   our                )
(dada-test-share my                our                atomic     (our (atomic) ())                   (shared Lease-id)  (Lease-id shared ()))
(dada-test-share my                (shared Lease-id)  var        (our ()       (Lease-id))           (shared Lease-id)  (Lease-id shared ()))
(dada-test-share my                (shared Lease-id)  shared     (our ()       (Lease-id))           (shared Lease-id)  (Lease-id shared ()))
(dada-test-share my                (shared Lease-id)  atomic     (our (atomic) (Lease-id))           (shared Lease-id1) (Lease-id1 shared (Lease-id)))
(dada-test-share (lent Lease-id)   my                 var        (my  ()       (Lease-id))           (shared Lease-id1) (Lease-id1 shared (Lease-id)))
(dada-test-share (lent Lease-id)   my                 shared     (our ()       (Lease-id))           (shared Lease-id1) (Lease-id1 shared (Lease-id)))
(dada-test-share (lent Lease-id)   my                 atomic     (my  (atomic) (Lease-id))           (shared Lease-id1) (Lease-id1 shared (Lease-id)))
(dada-test-share (lent Lease-id)   our                var        (our ()       (Lease-id))           (shared Lease-id1) (Lease-id1 shared (Lease-id)))
(dada-test-share (lent Lease-id)   our                shared     (our ()       (Lease-id))           (shared Lease-id1) (Lease-id1 shared (Lease-id)))
(dada-test-share (lent Lease-id)   our                atomic     (our (atomic) (Lease-id))           (shared Lease-id1) (Lease-id1 shared (Lease-id)))
(dada-test-share (lent Lease-id)   (shared Lease-id1) var        (our ()       (Lease-id Lease-id1)) (shared Lease-id2) (Lease-id2 shared (Lease-id Lease-id1)))
(dada-test-share (lent Lease-id)   (shared Lease-id1) shared     (our ()       (Lease-id Lease-id1)) (shared Lease-id2) (Lease-id2 shared (Lease-id Lease-id1)))
(dada-test-share (lent Lease-id)   (shared Lease-id1) atomic     (our (atomic) (Lease-id Lease-id1)) (shared Lease-id2) (Lease-id2 shared (Lease-id Lease-id1)))
(dada-test-share (lent Lease-id)   (lent Lease-id1)   var        (my  ()       (Lease-id Lease-id1)) (shared Lease-id2) (Lease-id2 shared (Lease-id Lease-id1)))
(dada-test-share (lent Lease-id)   (lent Lease-id1)   shared     (our ()       (Lease-id Lease-id1)) (shared Lease-id2) (Lease-id2 shared (Lease-id Lease-id1)))
(dada-test-share (lent Lease-id)   (lent Lease-id1)   atomic     (my  (atomic) (Lease-id Lease-id1)) (shared Lease-id2) (Lease-id2 shared (Lease-id Lease-id1)))
(dada-test-share our               my                 var        (our ()       ())                   our                )
(dada-test-share our               my                 shared     (our ()       ())                   our                )
(dada-test-share our               my                 atomic     (our ()       ())                   our                )
(dada-test-share our               (lent Lease-id1)   var        (our ()       ())                   our                )
(dada-test-share our               (lent Lease-id1)   shared     (our ()       ())                   our                )
(dada-test-share our               (lent Lease-id1)   atomic     (our ()       ())                   our                )
(dada-test-share our               our                var        (our ()       ())                   our                )
(dada-test-share our               our                shared     (our ()       ())                   our                )
(dada-test-share our               our                atomic     (our ()       ())                   our                )
(dada-test-share our               (shared Lease-id1) var        (our ()       ())                   our                )
(dada-test-share our               (shared Lease-id1) shared     (our ()       ())                   our                )
(dada-test-share our               (shared Lease-id1) atomic     (our ()       ())                   our                )
(dada-test-share (shared Lease-id) my                 var        (our ()       (Lease-id))           (shared Lease-id)  (Lease-id shared ()))
(dada-test-share (shared Lease-id) my                 shared     (our ()       (Lease-id))           (shared Lease-id)  (Lease-id shared ()))
(dada-test-share (shared Lease-id) my                 atomic     (our ()       (Lease-id))           (shared Lease-id)  (Lease-id shared ()))
(dada-test-share (shared Lease-id) (lent Lease-id1)   var        (our ()       (Lease-id))           (shared Lease-id)  (Lease-id shared ()))
(dada-test-share (shared Lease-id) (lent Lease-id1)   shared     (our ()       (Lease-id))           (shared Lease-id)  (Lease-id shared ()))
(dada-test-share (shared Lease-id) (lent Lease-id1)   atomic     (our ()       (Lease-id))           (shared Lease-id)  (Lease-id shared ()))
(dada-test-share (shared Lease-id) our                var        (our ()       (Lease-id))           (shared Lease-id)  (Lease-id shared ()))
(dada-test-share (shared Lease-id) our                shared     (our ()       (Lease-id))           (shared Lease-id)  (Lease-id shared ()))
(dada-test-share (shared Lease-id) our                atomic     (our ()       (Lease-id))           (shared Lease-id)  (Lease-id shared ()))
(dada-test-share (shared Lease-id) (shared Lease-id1) var        (our ()       (Lease-id))           (shared Lease-id)  (Lease-id shared ()))
(dada-test-share (shared Lease-id) (shared Lease-id1) shared     (our ()       (Lease-id))           (shared Lease-id)  (Lease-id shared ()))
(dada-test-share (shared Lease-id) (shared Lease-id1) atomic     (our ()       (Lease-id))           (shared Lease-id)  (Lease-id shared ()))

; Patterns to test:
;
;               Inner             Outer              Field type Perm when given    Old value        Leases and comments
;               --------------    -----------        ---------- ------------------ --------------   ----------------------------
(dada-test-give my                my                 var        my                 expired          )
(dada-test-give my                my                 shared     our                (my box _)       ) ; Because its a shared field, the "my" is interpreted as our
(dada-test-give my                my                 atomic     my                 expired          ) ; Unique access to atomic: still atomic
(dada-test-give my                (lent Lease-id)    var        (lent Lease-id1)   (my box _)       (Lease-id1 lent (Lease-id)))
(dada-test-give my                (lent Lease-id)    shared     (shared Lease-id1) (my box _)       (Lease-id1 shared (Lease-id)))
(dada-test-give my                (lent Lease-id)    atomic     (lent Lease-id1)   (my box _)       (Lease-id1 lent (Lease-id)))
(dada-test-give my                our                var        our                (my box _)       )
(dada-test-give my                our                shared     our                (my box _)       )
(dada-test-give my                our                atomic     (lent Lease-id)    (my box _)       (Lease-id lent ())) ; Can't leave a hole, and others can lend this value
(dada-test-give my                (shared Lease-id)  var        (shared Lease-id)  (my box _)       (Lease-id shared ()))
(dada-test-give my                (shared Lease-id)  shared     (shared Lease-id)  (my box _)       (Lease-id shared ()))
(dada-test-give my                (shared Lease-id)  atomic     (lent Lease-id1)   (my box _)       (Lease-id1 lent (Lease-id)))
(dada-test-give (lent Lease-id)   my                 var        (lent Lease-id1)   ((lent _) _ _)   (Lease-id1 lent (Lease-id)))
(dada-test-give (lent Lease-id)   my                 shared     (shared Lease-id1) ((lent _) _ _)   (Lease-id1 shared (Lease-id)))
(dada-test-give (lent Lease-id)   my                 atomic     (lent Lease-id1)   ((lent _) _ _)   (Lease-id1 lent (Lease-id)))
(dada-test-give (lent Lease-id)   our                var        (shared Lease-id1) ((lent _) _ _)   (Lease-id1 shared (Lease-id)))
(dada-test-give (lent Lease-id)   our                shared     (shared Lease-id1) ((lent _) _ _)   (Lease-id1 shared (Lease-id)))
(dada-test-give (lent Lease-id)   our                atomic     (lent Lease-id1)   ((lent _) _ _)   (Lease-id1 lent (Lease-id)))
(dada-test-give (lent Lease-id)   (shared Lease-id1) var        (shared Lease-id2) ((lent _) _ _)   (Lease-id2 shared (Lease-id Lease-id1)))
(dada-test-give (lent Lease-id)   (shared Lease-id1) shared     (shared Lease-id2) ((lent _) _ _)   (Lease-id2 shared (Lease-id Lease-id1)))
(dada-test-give (lent Lease-id)   (shared Lease-id1) atomic     (lent Lease-id2)   ((lent _) _ _)   (Lease-id2 lent (Lease-id Lease-id1)))
(dada-test-give (lent Lease-id)   (lent Lease-id1)   var        (lent Lease-id2)   ((lent _) _ _)   (Lease-id2 lent (Lease-id Lease-id1)))
(dada-test-give (lent Lease-id)   (lent Lease-id1)   shared     (shared Lease-id2) ((lent _) _ _)   (Lease-id2 shared (Lease-id Lease-id1)))
(dada-test-give (lent Lease-id)   (lent Lease-id1)   atomic     (lent Lease-id2)   ((lent _) _ _)   (Lease-id2 lent (Lease-id Lease-id1)))
(dada-test-give our               my                 var        our                (our box _)      )
(dada-test-give our               my                 shared     our                (our box _)      )
(dada-test-give our               my                 atomic     our                (our box _)      )
(dada-test-give our               (lent Lease-id1)   var        our                (our box _)      )
(dada-test-give our               (lent Lease-id1)   shared     our                (our box _)      )
(dada-test-give our               (lent Lease-id1)   atomic     our                (our box _)      )
(dada-test-give our               our                var        our                (our box _)      )
(dada-test-give our               our                shared     our                (our box _)      )
(dada-test-give our               our                atomic     our                (our box _)      )
(dada-test-give our               (shared Lease-id1) var        our                (our box _)      )
(dada-test-give our               (shared Lease-id1) shared     our                (our box _)      )
(dada-test-give our               (shared Lease-id1) atomic     our                (our box _)      )
(dada-test-give (shared Lease-id) my                 var        (shared Lease-id)  ((shared _) _ _) (Lease-id shared ()))
(dada-test-give (shared Lease-id) my                 shared     (shared Lease-id)  ((shared _) _ _) (Lease-id shared ()))
(dada-test-give (shared Lease-id) my                 atomic     (shared Lease-id)  ((shared _) _ _) (Lease-id shared ()))
(dada-test-give (shared Lease-id) (lent Lease-id1)   var        (shared Lease-id)  ((shared _) _ _) (Lease-id shared ()))
(dada-test-give (shared Lease-id) (lent Lease-id1)   shared     (shared Lease-id)  ((shared _) _ _) (Lease-id shared ()))
(dada-test-give (shared Lease-id) (lent Lease-id1)   atomic     (shared Lease-id)  ((shared _) _ _) (Lease-id shared ()))
(dada-test-give (shared Lease-id) our                var        (shared Lease-id)  ((shared _) _ _) (Lease-id shared ()))
(dada-test-give (shared Lease-id) our                shared     (shared Lease-id)  ((shared _) _ _) (Lease-id shared ()))
(dada-test-give (shared Lease-id) our                atomic     (shared Lease-id)  ((shared _) _ _) (Lease-id shared ()))
(dada-test-give (shared Lease-id) (shared Lease-id1) var        (shared Lease-id)  ((shared _) _ _) (Lease-id shared ()))
(dada-test-give (shared Lease-id) (shared Lease-id1) shared     (shared Lease-id)  ((shared _) _ _) (Lease-id shared ()))
(dada-test-give (shared Lease-id) (shared Lease-id1) atomic     (shared Lease-id)  ((shared _) _ _) (Lease-id shared ()))

; Patterns to test:
;
;               Inner             Outer              Field type Perm when lent     Leases and comments
;               --------------    -----------        ---------- ------------------ ----------------------------
(dada-test-lend my                my                 var        (lent Lease-id)    (Lease-id lent ()))
(dada-test-lend my                my                 shared     our                )
(dada-test-lend my                my                 atomic     (lent Lease-id)    (Lease-id lent ()))
(dada-test-lend my                (lent Lease-id)    var        (lent Lease-id1)   (Lease-id1 lent (Lease-id)))
(dada-test-lend my                (lent Lease-id)    shared     (shared Lease-id1) (Lease-id1 shared (Lease-id)))
(dada-test-lend my                (lent Lease-id)    atomic     (lent Lease-id1)   (Lease-id1 lent (Lease-id)))
(dada-test-lend my                our                var        our                )
(dada-test-lend my                our                shared     our                )
(dada-test-lend my                our                atomic     (lent Lease-id)    (Lease-id lent ()))
(dada-test-lend my                (shared Lease-id)  var        (shared Lease-id)  (Lease-id shared ()))
(dada-test-lend my                (shared Lease-id)  shared     (shared Lease-id)  (Lease-id shared ()))
(dada-test-lend my                (shared Lease-id)  atomic     (lent Lease-id1)   (Lease-id1 lent (Lease-id)))
(dada-test-lend (lent Lease-id)   my                 var        (lent Lease-id1)   (Lease-id1 lent (Lease-id)))
(dada-test-lend (lent Lease-id)   my                 shared     (shared Lease-id1) (Lease-id1 shared (Lease-id)))
(dada-test-lend (lent Lease-id)   my                 atomic     (lent Lease-id1)   (Lease-id1 lent (Lease-id)))
(dada-test-lend (lent Lease-id)   our                var        (shared Lease-id1) (Lease-id1 shared (Lease-id)))
(dada-test-lend (lent Lease-id)   our                shared     (shared Lease-id1) (Lease-id1 shared (Lease-id)))
(dada-test-lend (lent Lease-id)   our                atomic     (lent Lease-id1)   (Lease-id1 lent (Lease-id)))
(dada-test-lend (lent Lease-id)   (shared Lease-id1) var        (shared Lease-id2) (Lease-id2 shared (Lease-id Lease-id1)))
(dada-test-lend (lent Lease-id)   (shared Lease-id1) shared     (shared Lease-id2) (Lease-id2 shared (Lease-id Lease-id1)))
(dada-test-lend (lent Lease-id)   (shared Lease-id1) atomic     (lent Lease-id2)   (Lease-id2 lent (Lease-id Lease-id1)))
(dada-test-lend (lent Lease-id)   (lent Lease-id1)   var        (lent Lease-id2)   (Lease-id2 lent (Lease-id Lease-id1)))
(dada-test-lend (lent Lease-id)   (lent Lease-id1)   shared     (shared Lease-id2) (Lease-id2 shared (Lease-id Lease-id1)))
(dada-test-lend (lent Lease-id)   (lent Lease-id1)   atomic     (lent Lease-id2)   (Lease-id2 lent (Lease-id Lease-id1)))
(dada-test-lend our               my                 var        our                )
(dada-test-lend our               my                 shared     our                )
(dada-test-lend our               my                 atomic     our                )
(dada-test-lend our               (lent Lease-id1)   var        our                )
(dada-test-lend our               (lent Lease-id1)   shared     our                )
(dada-test-lend our               (lent Lease-id1)   atomic     our                )
(dada-test-lend our               our                var        our                )
(dada-test-lend our               our                shared     our                )
(dada-test-lend our               our                atomic     our                )
(dada-test-lend our               (shared Lease-id1) var        our                )
(dada-test-lend our               (shared Lease-id1) shared     our                )
(dada-test-lend our               (shared Lease-id1) atomic     our                )
(dada-test-lend (shared Lease-id) my                 var        (shared Lease-id)  (Lease-id shared ()))
(dada-test-lend (shared Lease-id) my                 shared     (shared Lease-id)  (Lease-id shared ()))
(dada-test-lend (shared Lease-id) my                 atomic     (shared Lease-id)  (Lease-id shared ()))
(dada-test-lend (shared Lease-id) (lent Lease-id1)   var        (shared Lease-id)  (Lease-id shared ()))
(dada-test-lend (shared Lease-id) (lent Lease-id1)   shared     (shared Lease-id)  (Lease-id shared ()))
(dada-test-lend (shared Lease-id) (lent Lease-id1)   atomic     (shared Lease-id)  (Lease-id shared ()))
(dada-test-lend (shared Lease-id) our                var        (shared Lease-id)  (Lease-id shared ()))
(dada-test-lend (shared Lease-id) our                shared     (shared Lease-id)  (Lease-id shared ()))
(dada-test-lend (shared Lease-id) our                atomic     (shared Lease-id)  (Lease-id shared ()))
(dada-test-lend (shared Lease-id) (shared Lease-id1) var        (shared Lease-id)  (Lease-id shared ()))
(dada-test-lend (shared Lease-id) (shared Lease-id1) shared     (shared Lease-id)  (Lease-id shared ()))
(dada-test-lend (shared Lease-id) (shared Lease-id1) atomic     (shared Lease-id)  (Lease-id shared ()))
